mynikkiproject/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nikki.urls')),
]

mynikkiproject/nikki/urls.py
from django.urls import path
from .views import NikkiList, NikkiDetail, NikkiCreate, NikkiUpdate, NikkiDelete, NikkiSearch

app_name = 'nikki'


urlpatterns = [
    path('nikki_list/', NikkiList.as_view(), name='nikki_list'),
    path('nikki_detail/<int:pk>/', NikkiDetail.as_view(), name='nikki_detail'),
    path('nikki_create/', NikkiCreate.as_view(), name='nikki_create'),
    path('nikki_update/<int:pk>/', NikkiUpdate.as_view(), name='nikki_update'),
    path('nikki_delete/<int:pk>/', NikkiDelete.as_view(), name='nikki_delete'),
    path('nikki_search/', NikkiSearch.as_view(), name='nikki_search'),
]

mynikkiproject/nikki/models.py
from django.db import models

# Create your models here.
class Nikki(models.Model):


    class Meta:
        db_table = 'nikki'


    title = models.CharField(max_length=100) # タイトル
    content = models.TextField(max_length=1000) # 内容
    create_at = models.DateField(auto_now_add=True) # 作成日時


    def __str__(self):
        return self.title

mynikkiproject/nikki/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from .models import Nikki

class NikkiList(ListView):
    model = Nikki
    template_name = 'nikki_list.html'

    
from django.views.generic import DetailView
from .models import Nikki

class NikkiDetail(DetailView):
    model =  Nikki
    template_name = 'nikki_detail.html'

    
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Nikki

class NikkiCreate(CreateView):
    model = Nikki
    template_name = 'nikki_create.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('nikki:nikki_list')

    
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from .models import Nikki

class NikkiUpdate(UpdateView):
    model = Nikki
    template_name = 'nikki_update.html'
    fields = ['title', 'content']
    success_url = reverse_lazy('nikki:nikki_list')


from django.views.generic import DeleteView
from django.urls import reverse_lazy
from .models import Nikki

class NikkiDelete(DeleteView):
    model = Nikki
    template_name = 'nikki_delete.html'
    success_url = reverse_lazy('nikki:nikki_list')


class NikkiSearch(ListView):
    model = Nikki
    template_name = 'nikki_search.html'


    def get_queryset(self):
        query = super().get_queryset()
        title = self.request.GET.get('title', None)
        if title:
            query = query.filter(title__icontains=title)
        return query
   
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.request.GET.get('title', '')
        return context

mynikkiproject/templates/base.html
<!DOCTYPE html>
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    </head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

mynikkiproject/templates/nikki_create.html
{% extends "base.html" %}


{% block title %}日記作成{% endblock %}


{% block content %}
<div class="container my-3">
    <h2 class="text-center my-3">日記作成</h2>


    {% load django_bootstrap5 %}


    <div class="container my-3" style="max-width:700px">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="form-control btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
</div>
{% endblock %}

mynikkiproject/templates/nikki_delete.html
{% extends "base.html" %}


{% block title %}日記削除{% endblock %}


{% block content %}
<div class="container my-3">
    <h2>日記削除</h2>
    <p>本当に削除しますか</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Submit">
    </form>
</div>
{% endblock %}

mynikkiproject/templates/nikki_detail.html
{% extends "base.html" %}


{% block title %}日記詳細{% endblock %}


{% block content %}
<div class="container my-3">
    <div class="card my-3">
        <div class="card-body">
            <h5 class="card-title">タイトル: {{ object.title }}</h5>
            <p class="card-text">{{ object.content|linebreaksbr }}</p>
            <a href="{% url 'nikki:nikki_update' object.id %}" class="btn btn-secondary ms-3" tabindex="-1" role="button" aria-disabled="true">編集</a>
            <a href="{% url 'nikki:nikki_delete' object.id %}" class="btn btn-danger ms-3" tabindex="-1" role="button" aria-disabled="true">削除</a>
        </div>
    </div>
</div>


{% endblock %}

mynikkiproject/templates/nikki_list.html
{% extends "base.html" %}

{% block title %}日記一覧{% endblock %}

{% block content %}

<div class="container my-3">

    <h2>日記一覧 <a href="{% url 'nikki:nikki_create'%}" class="btn btn-primary ms-3" tabindex="-1" role="button" aria-disabled="true">作成</a></h2>

    {% for object in object_list %}

        <div class="card my-3">

            <div class="card-body">

                <h5 class="card-title">タイトル: <a href="{% url 'nikki:nikki_detail' object.id %}">{{object.title}}</a></h5>

                <p class="card-text">{{object.content|truncatechars_html:20|linebreaksbr}}</p>

            </div>

        </div>

    {% endfor %}

</div>

{% endblock %}

mynikkiproject/templates/nikki_search.html
{% extends "base.html" %}


{% block title %}Search{% endblock title %}


{% block content %}
<div class="container mt-3">
    <h2 class="mt-5">Search</h2>
    <form class="w-50" method="GET" action="{% url 'nikki:nikki_search' %}">
        <p><input class="form-control" type="text" name="title" value="{{ title }}" placeholder="キーワード入力"></p>
        <p><input class="btn btn-secondary" type="submit" value="検索"></p>
    </form>


    {% for object in object_list %}
        <div class="card my-3">
            <div class="card-body">
                <h5 class="card-title">タイトル: <a href="{% url 'nikki:nikki_detail' object.id %}">{{object.title}}</a></h5>
                <p class="card-text">{{object.content|truncatechars_html:20|linebreaksbr}}</p>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock content %}

mynikkiproject/templates/nikki_update.html
{% extends "base.html" %}


{% block title %}日記編集{% endblock %}


{% block content %}
<div class="container my-3">
    <h2 class="text-center my-3">日記編集</h2>


    {% load django_bootstrap5 %}


    <div class="container my-3" style="max-width:700px">
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="form-control btn btn-primary" type="submit" value="Submit">
        </form>
    </div>
</div>


{% endblock %}